# Generated by Django 5.0.2 on 2024-03-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animes',
            new_name='Anime',
        ),
        migrations.RenameModel(
            old_name='Deportes',
            new_name='Deporte',
        ),
        migrations.RenameModel(
            old_name='Videojuegos',
            new_name='Videojuego',
        ),
    ]
